// Generated by CoffeeScript 1.8.0
var margin;

margin = {
  left: 60,
  top: 40,
  right: 40,
  bottom: 40,
  inner: 5
};

d3.json("qtlcharts/inst/panels/heatmap/test/data.json", function(data) {
  var h, mychart, w;
  h = 300;
  w = 300;
  mychart = heatmap().height(h).width(w);
  return d3.select("div#heatmap").datum(data).call(mychart);
});
