// Generated by CoffeeScript 1.8.0
var margin;

margin = {
  left: 60,
  top: 40,
  right: 40,
  bottom: 40,
  inner: 5
};

d3.json("qtlcharts/inst/panels/lodchart/test/data.json", function(data) {
  var chrrect, h, mychart, w;
  h = 300;
  w = 600;
  mychart = lodchart().lodvarname("lod.em").height(h).width(w).margin(margin);
  d3.select("div#lodchart").datum(data).call(mychart);
  chrrect = mychart.chrSelect();
  chrrect.on("mouseover", function() {
    return d3.select(this).attr("fill", "#E9CFEC");
  }).on("mouseout", function(d, i) {
    return d3.select(this).attr("fill", function() {
      if (i % 2) {
        return d3.rgb(200, 200, 200);
      }
      return d3.rgb(230, 230, 230);
    });
  });
  return mychart.markerSelect().on("click", function(d) {
    var r;
    r = d3.select(this).attr("r");
    return d3.select(this).transition().duration(500).attr("r", r * 3).transition().duration(500).attr("r", r);
  });
});
