// Generated by CoffeeScript 1.8.0
var margin;

margin = {
  left: 60,
  top: 40,
  right: 40,
  bottom: 40,
  inner: 5
};

d3.json("qtlcharts/inst/panels/cichart/test/data.json", function(data) {
  var h, mychart, w, x;
  data.means = (function() {
    var _i, _len, _ref, _results;
    _ref = data.means;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      x = _ref[_i];
      _results.push(x * 3 - 60);
    }
    return _results;
  })();
  data.low = (function() {
    var _i, _len, _ref, _results;
    _ref = data.low;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      x = _ref[_i];
      _results.push(x * 3 - 60);
    }
    return _results;
  })();
  data.high = (function() {
    var _i, _len, _ref, _results;
    _ref = data.high;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      x = _ref[_i];
      _results.push(x * 3 - 60);
    }
    return _results;
  })();
  data.categories = ["AA", "AB", "BB"];
  h = 300;
  w = 200;
  mychart = cichart().height(h).width(w).xlab("Genotype").ylab("Phenotype");
  return d3.select("div#cichart").datum(data).call(mychart);
});
